export const actionTypes = {
    CREATE_ITEM: 'CREATE_ITEM',
    DELETE_ITEM: 'DELETE_ITEM',
    SHOW_ITEM: 'SHOW_ITEM',
    SAVE_ITEM: 'SAVE_ITEM',
    SORT_ITEMS:'SORT_ITEMS',
    DOWNLOAD_ITEMS_FROM_LS: 'DOWNLOAD_FROM_LS',
};
